#!/bin/bash
#!/bin/bash
if [ -e check_mine.s ]; then 
  rm check_mine.s 
fi
if [ -e check_expected.s ]; then 
  rm check_expected.s 
fi
../../bin/lexer $1 | ../../bin/parser $1 | ../../bin/semant $1 | ./cgen > check_mine.s 2>&1
../../bin/lexer $1 | ../../bin/parser $1 | ../../bin/semant $1 | ../../bin/cgen > check_expected.s 2>&1

if [ -e code_result_mine.txt ]; then 
  rm code_result_mine.txt 
fi
if [ -e code_result_expected.txt ]; then 
  rm code_result_expected.txt 
fi

../../bin/spim -file check_mine.s > code_result_mine.txt 2>&1
../../bin/spim -file check_expected.s > code_result_expected.txt 2>&1
result=$(diff code_result_mine.txt code_result_expected.txt)

if [ -z "$result" ]; then 
  echo "passed"
else 
  echo "$result"
fi